## Getting Started

## 1. Clonse the repo 
```bash
git clone https://github.com/your-username/backend-foundation.git
cd backend-foundation

### 2. Github Actions -
```yaml
name: Run Jest Tests

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test